### ISSUE TITLE
How to deal with multiple Models in the same paper?

### ISSUE THREAD

**Issue by nickhaf** [formal-methods-mpi/Taxonomy.jl#23]
What was the result of our discussion? :D Do we make an own record for every model, even if they stem from the same paper?

**Comment by aaronpeikert** [comment]
This actually works. Simply add more than one taxon in a vector:

https://github.com/StructuralEquationModels/Taxonomy.jl/blob/f75706f583f88782ec57a55571085b21c18a95aa/src/record.jl#L5

But we should add a testcase for that.

**Comment by nickhaf** [comment]
Yes, but can we also deal with a case where other record variables like spec or data are only available for some taxons? Don`t know if thats necessary though.

**Comment by aaronpeikert** [comment]
If other metadata differs, we simply can create multiple entries with different ids.

**Comment by LeonieHagitte** [comment]
so I understand that this (specifying several models of one paper) is possible, but I currently have problems implementing this, as I am not sure where to expand the vector and how to assign the respective terms so that they don't get mixed up
