### ISSUE TITLE
Doi SEM Paper for rating

### ISSUE THREAD

**Issue by CliffBod** [formal-methods-mpi/Taxonomy.jl#26]
10.1037/emo0000769

10.1177/1073191120905892

10.1037/ebs0000266

10.1037/fam0000902

10.24193/jebp.2022.1.1

10.1037/emo0000946

10.1002/hbm.25403

10.1037/cou0000555

10.3389/fpsyg.2022.797443

**Comment by LeonieHagitte** [comment]
10.1177/1073191120905892
10.1002/hbm.25403
10.3389/fpsyg.2022.797443

Those are the only ones I can get access to the full text.
