### ISSUE TITLE
What to do if the location of a Judgement is not specified?

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Taxonomy.jl#77]
atm, this is simply converted to `missing`. I think this behavior encourages coders to forget to specify this. 
Maybe either ask to specifically code `missing` or throw a warning.

**Comment by aaronpeikert** [comment]
#92

**Comment by aaronpeikert** [comment]
No not for all judgments for efficiency, but on taxon level reasonable.
