### ISSUE TITLE
Multigroup models should have their own type

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Taxonomy.jl#80]
The documentation of the CFA Taxon says  

>  `n_sample`: Number of observed cases. May be between different taxons from same paper sometime, e.g. multigroup models.

However, I believe Multigroup models should be their own Taxon to preserve the information that those models are indeed Multigroup models. In this case, we need to label the parameters to indicate their restrictions across groups.

**Comment by aaronpeikert** [comment]
We should create a very simple wrapper type that simply contains a vector of taxons.

**Comment by aaronpeikert** [comment]
is on the roadmap
